// -----------------------------------------------------------------------------
// csvrow.h
// Rawser Spicer
// date created: 2014/04/09
// modified: 2014/04/14
//
//  this data structure represents a row in the csv files generated by the
// site creator program
//
// -----------------------------------------------------------------------------
#ifndef CSVROW_H
#define CSVROW_H

#include <QString>

// -----------------------------------------------------------------------------
// CsvRow
//  a row in the gennerated csv file
// -----------------------------------------------------------------------------
struct CsvRow
{
public:
    // members representing feilds in the row
    QString d_element, Data_type, array_pos, Coef1, Coef2, Coef3, Coef4,
            Coef5, Coef6, Coef7, QC_high, QC_low, QC_step, out_name,
            out_units, out_tpye;

    // -------------------------------------------------------------------------
    // constructor
    //      allows a row to be created with client values
    // preconditions:
    //      none but all values should be type of argument if provided
    // postconditions:
    //      members corispopnding to arguments will be initilized with values
    //  provided. all other members default to zero.
    // -------------------------------------------------------------------------
    CsvRow(QString element = "def", QString dtyp ="num", int pos = 0,
           QString units="ignore", QString type ="ignore"):
            d_element(element), Data_type(dtyp),
            array_pos(std::to_string(pos).c_str()), Coef1("0"),
            Coef2("0"), Coef3("0"), Coef4("0"), Coef5("0"), Coef6("0"),
            Coef7("0"), QC_high("0"), QC_low("0"), QC_step("0"),
            out_name(element), out_units(units), out_tpye(type){}

    // -------------------------------------------------------------------------
    // to_str
    //      this function converts the internal data to a QString
    // preconditions:
    //      none
    // postconditions:
    //      returns a comma seperated Qstring of the data
    // -------------------------------------------------------------------------
    QString to_str(){
        return d_element + "," + Data_type + "," + array_pos + "," +
               Coef1 + "," + Coef2 + "," + Coef3 + "," + Coef4 + "," +
               Coef5 + "," + Coef6 + "," + Coef7 + "," + QC_high + "," +
               QC_low + "," + QC_step + "," + out_name + "," +
               out_units + "," + out_tpye ;}
}; // end of CsvRow

#endif // CSVROW_H
